### ISSUE TITLE
Style asset-metadata

### ISSUE THREAD

**Issue by vpetersson** [Screenly/playground#10]
We need to create a sleek looking design for [asset-metadata](https://github.com/Screenly/playground/tree/master/asset-metadata). I'd like to have a nice single screen that includes a map that uses the coordinates.

Acceptance Criteria:
- [x] Create design (@L4cko)
- [x] Implement design

**Comment by vpetersson** [comment]
@L4cko Please provide your design.

**Comment by L4cko** [comment]
Figma designs links
https://www.figma.com/file/U0awkNQKLDKmOP7k9xiZUQ/WA-Review?node-id=3333%3A19947

**Comment by L4cko** [comment]
Design
https://www.figma.com/file/U0awkNQKLDKmOP7k9xiZUQ/WA-Review?node-id=3318%3A19693

Map style
https://snazzymaps.com/style/1443/cleaner-midnight

**Comment by vpetersson** [comment]
@L4cko what maps is this compatible with? Is it tiles for open street maps?

**Comment by L4cko** [comment]
> 

I'm not sure, to be honest. I just use snazzy maps for different map styling. You can use this design code probably. @vpetersson

**Comment by iamplugged** [comment]
Dev in progress
