### ISSUE TITLE
Fix bugs in clock Edge App

### ISSUE THREAD

**Issue by vpetersson** [Screenly/Playground#109]
* Right now we write the date like this: "11 August, 2023". That's not how you would normally write it. Normally, you'd write it as "August 11, 2023"
* When using a UK locale, I get the time in AM/PM. This is not expected. What's expected is 24h mode, so let's make this contingent on the location.

**Comment by salmanfarisvp** [comment]
Already there is a PR https://github.com/Screenly/Playground/pull/121

**Comment by salmanfarisvp** [comment]
Fixed on https://github.com/Screenly/Playground/pull/121
