### ISSUE TITLE
Create Google Calendar Edge App

### ISSUE THREAD

**Issue by vpetersson** [Screenly/Playground#140]
We should create a Google Calendar Edge App. It should be fairly straight forward to accomplish based on the quickstart guide.

The goal is to show a weekly/daily calendar in full screen mode.

We would need to define some settings, including:

* `CLIENT_ID` (setting)
* `API_KEY` (secret)
* Possibly calendar ID

# References

* [JS Library](https://github.com/google/google-api-javascript-client)
* [JavaScript Quickstart](https://developers.google.com/calendar/api/quickstart/js)

**Comment by salmanfarisvp** [comment]
Moved to Edge App List.
