### ISSUE TITLE
JavaScript Injector: ESRI ArcGIS Dashboard

### ISSUE THREAD

**Issue by Eric-Screenly** [Screenly/Playground#144]
A user wants the ability to log in to their ArcGIS Dashboard.

https://www.esri.com/en-us/arcgis/products/arcgis-online/overview
https://www.esri.com/en-us/home

Example URL: https://gis.[company-name.com]/portal/apps/dashboards/[dashboard-id]

Message me for test URL and login credentials.

**Comment by salmanfarisvp** [comment]
Moved to Edge App List
