### ISSUE TITLE
Edge App deploy workflow steps should also be failed on CLI command fails

### ISSUE THREAD

**Issue by rusko124** [Screenly/Playground#154]
An example workflow: https://github.com/Screenly/Playground/actions/runs/7545920425/job/20542576908

The Deploy Edge App step is successful, but the CLI command returned an error: ` Failed to upload edge app: App id cannot be empty. Provide it either in manifest or with --app-id..`

**Comment by vpetersson** [comment]
The run now fails as it should:
https://github.com/Screenly/Playground/actions/runs/7545920425/job/20566666318

Closing.
