### ISSUE TITLE
JavaScript Injector: Zoom Meetings

### ISSUE THREAD

**Issue by Eric-Screenly** [Screenly/Playground#33]
We're experimenting with using Zoom on a Screenly player for screen sharing for a customer. When you follow this URL to join the personal meeting room it will ask you if you want to download Zoom: we want to say no to that. Then we need to click where it says "Join from Your Browser" in order to join the meeting, and after we may need to click the "Join with computer audio" button.

**Comment by salmanfarisvp** [comment]
Moved to Edge App List.
