### ISSUE TITLE
Create 'visitor check-in' app

### ISSUE THREAD

**Issue by vpetersson** [Screenly/Playground#47]
I was looking at a sample app from [Dark](https://darklang.com/), and they show how to make a simple [visitor check-in app](https://www.youtube.com/watch?v=orRn2kTtRXQ).

The process is pretty easy: 

* Select an employee out of a drop down list (probably stored in an SQLite database, or just hard coded in MVP)
* Enter your name, email and phone number along with a message
* When the user press submit, two alerts are sent:
  * SMS via Twilio
  * DM on Slack

**Comment by salmanfarisvp** [comment]
Moved to Edge App List.
