### ISSUE TITLE
JS Injector for Tableau GDPR concent 

### ISSUE THREAD

**Issue by vpetersson** [Screenly/Playground#94]
One of the demo assets we use is the [Tableau public dashboard](http://public.tableau.com/profile/tableau.core.product.marketing#!/vizhome/shared/XKGR9WQWY). However, when this loads, we get this:

<img width="1277" alt="Screenshot 2023-06-16 at 10 12 53 AM" src="https://github.com/Screenly/Playground/assets/357664/914bf6d9-df8e-4a63-af34-f3942a6b76f6">

Please create a JS injector script that closes this.

**Comment by salmanfarisvp** [comment]
Moved to Edge App List.
